name: "my joke action"

descriotion: "use an eternal API to retrieve and display a joke"

outputs:
  joke-output:
    description: "The resulting jokes from the icanhazdadjokes API"
    
runs:
  using: "node12"
  main: "main.js"